NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems.


The NumPy library contains multidimensional array and matrix data structures (you’ll find more information about this in later sections). It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

pip install numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.22.2'

# numpy array

In [3]:
arr = np.array([100,200,300,400,500])

In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
print(arr)

[100 200 300 400 500]


In [7]:
arr2 = np.array([
    [10,20,30,40,50],
    [100,200,300,400,500],
    [60,70,80,90,100]
])

In [8]:
print(arr2)

[[ 10  20  30  40  50]
 [100 200 300 400 500]
 [ 60  70  80  90 100]]


<img src="https://miro.medium.com/max/1330/1*s6gKy2DZ_300dgAeHPgjkQ.png">

In [10]:
arr3 = np.array([1,2,3,4,5],dtype='float32')

In [11]:
arr3

array([1., 2., 3., 4., 5.], dtype=float32)

In [12]:
arr2

array([[ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500],
       [ 60,  70,  80,  90, 100]])

In [14]:
arr2.shape

(3, 5)

In [15]:
arr3.shape

(5,)

In [16]:
# reshaping the array

In [17]:
arr4 = np.array([
    [10,20,30],
    [40,50,60]
    
])

In [19]:
arr4

array([[10, 20, 30],
       [40, 50, 60]])

In [20]:
arr4.shape

(2, 3)

In [22]:
arr5 = arr4.reshape(3,2)

In [23]:
print(arr5)

[[10 20]
 [30 40]
 [50 60]]


In [25]:
arr5.shape

(3, 2)

In [28]:
num = np.arange(1,21)

In [30]:
num1 = num.reshape(4,5)

In [31]:
num1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [33]:
num2 = np.arange(31,51).reshape(5,4)

In [34]:
num2

array([[31, 32, 33, 34],
       [35, 36, 37, 38],
       [39, 40, 41, 42],
       [43, 44, 45, 46],
       [47, 48, 49, 50]])

In [35]:
num2.dtype

dtype('int64')

In [37]:
num3 = num2.astype('float64')

In [38]:
num3

array([[31., 32., 33., 34.],
       [35., 36., 37., 38.],
       [39., 40., 41., 42.],
       [43., 44., 45., 46.],
       [47., 48., 49., 50.]])

In [39]:
num3.dtype

dtype('float64')

In [40]:
num3.itemsize    

8

In [43]:
zero_mat = np.zeros((10,10),dtype='int64')

In [44]:
zero_mat

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [45]:
zero_mat.shape

(10, 10)

In [46]:
ones_mat = np.ones((10,10))

In [47]:
print(ones_mat)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [54]:
mat = np.linspace(1,3,50).reshape(5,10)

In [55]:
mat

array([[1.        , 1.04081633, 1.08163265, 1.12244898, 1.16326531,
        1.20408163, 1.24489796, 1.28571429, 1.32653061, 1.36734694],
       [1.40816327, 1.44897959, 1.48979592, 1.53061224, 1.57142857,
        1.6122449 , 1.65306122, 1.69387755, 1.73469388, 1.7755102 ],
       [1.81632653, 1.85714286, 1.89795918, 1.93877551, 1.97959184,
        2.02040816, 2.06122449, 2.10204082, 2.14285714, 2.18367347],
       [2.2244898 , 2.26530612, 2.30612245, 2.34693878, 2.3877551 ,
        2.42857143, 2.46938776, 2.51020408, 2.55102041, 2.59183673],
       [2.63265306, 2.67346939, 2.71428571, 2.75510204, 2.79591837,
        2.83673469, 2.87755102, 2.91836735, 2.95918367, 3.        ]])

In [56]:
arr = np.arange(10,21)

In [57]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [58]:
arr[0]

10

In [59]:
arr[-1]

20

In [61]:
arr[2:8]

array([12, 13, 14, 15, 16, 17])

In [62]:
arr[2:8:2]

array([12, 14, 16])

In [63]:
mul_d = np.arange(1,21).reshape(5,4)

In [64]:
mul_d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [71]:
mul_d[0][3]

4

In [78]:
mul_d[0:5,1:2]

array([[ 2],
       [ 6],
       [10],
       [14],
       [18]])

In [81]:
mul_d[0:5,3:4]

array([[ 4],
       [ 8],
       [12],
       [16],
       [20]])

In [85]:
mul_d[0:5:2,2:3]

array([[ 3],
       [11],
       [19]])

In [87]:
arr.ndim

1

In [88]:
mul_d.ndim

2