NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems.


The NumPy library contains multidimensional array and matrix data structures (you’ll find more information about this in later sections). It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

pip install numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.22.2'

# numpy array

In [3]:
arr = np.array([100,200,300,400,500])

In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
print(arr)

[100 200 300 400 500]


In [6]:
arr2 = np.array([
    [10,20,30,40,50],
    [100,200,300,400,500],
    [60,70,80,90,100]
])

In [7]:
print(arr2)

[[ 10  20  30  40  50]
 [100 200 300 400 500]
 [ 60  70  80  90 100]]


<img src="https://miro.medium.com/max/1330/1*s6gKy2DZ_300dgAeHPgjkQ.png">

In [8]:
arr3 = np.array([1,2,3,4,5],dtype='float32')

In [9]:
arr3

array([1., 2., 3., 4., 5.], dtype=float32)

In [10]:
arr2

array([[ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500],
       [ 60,  70,  80,  90, 100]])

In [11]:
arr2.shape

(3, 5)

In [12]:
arr3.shape

(5,)

In [13]:
# reshaping the array

In [14]:
arr4 = np.array([
    [10,20,30],
    [40,50,60]
    
])

In [15]:
arr4

array([[10, 20, 30],
       [40, 50, 60]])

In [16]:
arr4.shape

(2, 3)

In [17]:
arr5 = arr4.reshape(3,2)

In [18]:
print(arr5)

[[10 20]
 [30 40]
 [50 60]]


In [19]:
arr5.shape

(3, 2)

In [20]:
num = np.arange(1,21)

In [21]:
num1 = num.reshape(4,5)

In [22]:
num1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [23]:
num2 = np.arange(31,51).reshape(5,4)

In [24]:
num2

array([[31, 32, 33, 34],
       [35, 36, 37, 38],
       [39, 40, 41, 42],
       [43, 44, 45, 46],
       [47, 48, 49, 50]])

In [25]:
num2.dtype

dtype('int64')

In [26]:
num3 = num2.astype('float64')

In [27]:
num3

array([[31., 32., 33., 34.],
       [35., 36., 37., 38.],
       [39., 40., 41., 42.],
       [43., 44., 45., 46.],
       [47., 48., 49., 50.]])

In [28]:
num3.dtype

dtype('float64')

In [29]:
num3.itemsize    

8

In [30]:
zero_mat = np.zeros((10,10),dtype='int64')

In [31]:
zero_mat

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [32]:
zero_mat.shape

(10, 10)

In [33]:
ones_mat = np.ones((10,10))

In [34]:
print(ones_mat)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [35]:
mat = np.linspace(1,3,50).reshape(5,10)

In [36]:
mat

array([[1.        , 1.04081633, 1.08163265, 1.12244898, 1.16326531,
        1.20408163, 1.24489796, 1.28571429, 1.32653061, 1.36734694],
       [1.40816327, 1.44897959, 1.48979592, 1.53061224, 1.57142857,
        1.6122449 , 1.65306122, 1.69387755, 1.73469388, 1.7755102 ],
       [1.81632653, 1.85714286, 1.89795918, 1.93877551, 1.97959184,
        2.02040816, 2.06122449, 2.10204082, 2.14285714, 2.18367347],
       [2.2244898 , 2.26530612, 2.30612245, 2.34693878, 2.3877551 ,
        2.42857143, 2.46938776, 2.51020408, 2.55102041, 2.59183673],
       [2.63265306, 2.67346939, 2.71428571, 2.75510204, 2.79591837,
        2.83673469, 2.87755102, 2.91836735, 2.95918367, 3.        ]])

In [37]:
arr = np.arange(10,21)

In [38]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [39]:
arr[0]

10

In [40]:
arr[-1]

20

In [41]:
arr[2:8]

array([12, 13, 14, 15, 16, 17])

In [42]:
arr[2:8:2]

array([12, 14, 16])

In [62]:
mul_d = np.arange(1,21).reshape(5,4)

In [44]:
mul_d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [45]:
mul_d[0][3]

4

In [46]:
mul_d[0:5,1:2]

array([[ 2],
       [ 6],
       [10],
       [14],
       [18]])

In [47]:
mul_d[0:5,3:4]

array([[ 4],
       [ 8],
       [12],
       [16],
       [20]])

In [48]:
mul_d[0:5:2,2:3]

array([[ 3],
       [11],
       [19]])

In [49]:
arr.ndim

1

In [50]:
mul_d.ndim

2

In [51]:
print(mul_d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [52]:
mul_d > 5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [53]:
mul_d[mul_d>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [58]:
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([60,70,80,90,100])

In [55]:
arr1 + arr2

array([ 70,  90, 110, 130, 150])

In [56]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([60,70,80,90,100])

In [57]:
arr1+arr2

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [59]:
arr1-arr2

array([-50, -50, -50, -50, -50])

In [60]:
arr1*arr2

array([ 600, 1400, 2400, 3600, 5000])

In [61]:
arr1 / arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [63]:
print(mul_d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [64]:
arr1 = np.array([10,20,30,40])

In [65]:
arr1

array([10, 20, 30, 40])

In [66]:
mul_d + arr1

array([[11, 22, 33, 44],
       [15, 26, 37, 48],
       [19, 30, 41, 52],
       [23, 34, 45, 56],
       [27, 38, 49, 60]])

In [67]:
arr1

array([10, 20, 30, 40])

In [68]:
for item in arr1:
    print(item)

10
20
30
40


In [70]:
for item in range(0,len(arr1)):
    print(item,arr1[item])

0 10
1 20
2 30
3 40


In [71]:
mul_d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [72]:
for item in mul_d:
    print(item)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]
[17 18 19 20]


In [75]:
for item in np.nditer(mul_d):
    print(item)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [76]:
mul_d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [77]:
mul_d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [79]:
mul_d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [80]:
arr1 = np.arange(12).reshape(4,3)

In [81]:
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [82]:
np.transpose(arr1)

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [83]:
arr1 = np.array([[1,2],[3,4]])

In [84]:
arr1

array([[1, 2],
       [3, 4]])

In [85]:
arr2 = np.array([[5,6],[7,8]])

In [86]:
arr2

array([[5, 6],
       [7, 8]])

In [89]:
np.concatenate((arr1,arr2),axis=0)  #axis 0 --- row wise

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [90]:
np.concatenate((arr1,arr2),axis=1)  #axis 1 -- col wise 

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [91]:
np.hstack((arr1,arr2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [92]:
np.vstack((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [101]:
arr3 = np.arange(8)

In [102]:
arr3

array([0, 1, 2, 3, 4, 5, 6, 7])

In [104]:
np.split(arr3,2)

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

In [105]:
arr4 = np.arange(16).reshape(4,4)

In [106]:
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [107]:
np.hsplit(arr4,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [109]:
np.vsplit(arr4,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [110]:
arr5 = np.array([[1,2,3],[4,5,6]])

In [111]:
arr5

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
np.append(arr5,[10,11,12])

array([ 1,  2,  3,  4,  5,  6, 10, 11, 12])

In [113]:
arr5

array([[1, 2, 3],
       [4, 5, 6]])

In [115]:
np.append(arr5,[[10,11,12]],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

In [119]:
np.append(arr5,[[13,14],[16,17]],axis=1)

array([[ 1,  2,  3, 13, 14],
       [ 4,  5,  6, 16, 17]])

In [120]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [125]:
arr6 = np.delete(arr,2)

In [123]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [127]:
arr6 = arr6.reshape(5,2)

In [128]:
arr6

array([[10, 11],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [129]:
np.delete(arr6,1,axis=0)

array([[10, 11],
       [15, 16],
       [17, 18],
       [19, 20]])

In [130]:
np.delete(arr6,1,axis=1)

array([[10],
       [13],
       [15],
       [17],
       [19]])

In [131]:
arr7 = np.array([4,5,6,7,8,9,4,5,6,7])

In [132]:
np.unique(arr7)

array([4, 5, 6, 7, 8, 9])

In [133]:
np.unique(arr7,return_index=True)

(array([4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5]))

In [134]:
np.char.add(['hello'],['world'])

array(['helloworld'], dtype='<U10')

In [136]:
np.char.multiply(['sleep'],3)

array(['sleepsleepsleep'], dtype='<U15')

In [137]:
np.char.center(['python'],10)

array(['  python  '], dtype='<U10')

In [138]:
np.char.center(['python'],10,fillchar='*')

array(['**python**'], dtype='<U10')

In [139]:
np.char.capitalize(['hello world'])

array(['Hello world'], dtype='<U11')

In [140]:
np.char.title(['hello world'])

array(['Hello World'], dtype='<U11')

In [141]:
np.char.upper(['punit'])

array(['PUNIT'], dtype='<U5')

In [142]:
np.char.lower(['MUMBAI'])

array(['mumbai'], dtype='<U6')

In [143]:
np.char.splitlines('Hello\nWelcome\n')

array(list(['Hello', 'Welcome']), dtype=object)

In [144]:
np.char.split('cricket,swimming,cooking',',')

array(list(['cricket', 'swimming', 'cooking']), dtype=object)

In [146]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [147]:
np.sin(arr)

array([-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525])

In [148]:
np.cos(arr)

array([-0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462,
        0.40808206])

In [149]:
np.tan(arr)

array([ 6.48360827e-01, -2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
        7.24460662e+00, -8.55993401e-01,  3.00632242e-01,  3.49391565e+00,
       -1.13731371e+00,  1.51589471e-01,  2.23716094e+00])

In [153]:
arr8 = np.arange(9).reshape(3,3)

In [154]:
arr8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [155]:
arr9 = np.array([1,2,3])

In [156]:
np.mod(arr8,arr9)

array([[0, 1, 2],
       [0, 0, 2],
       [0, 1, 2]])

In [159]:
2%3

2

In [160]:
np.remainder(arr8,arr9)

array([[0, 1, 2],
       [0, 0, 2],
       [0, 1, 2]])

In [161]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [162]:
np.sum(arr)

165

In [163]:
np.min(arr)

10

In [164]:
np.max(arr)

20

In [165]:
np.amin(arr)

10

In [166]:
np.amax(arr)

20

In [168]:
np.mean(arr)

15.0

In [169]:
np.median(arr)

15.0

In [170]:
np.std(arr)

3.1622776601683795

In [171]:
np.cov(arr)

array(11.)

In [172]:
np.var(arr)

10.0

In [174]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [197]:
arr = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [198]:
copied = np.copy(arr)

In [184]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [199]:
copied

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [200]:
arr.shape = 5,2

In [188]:
arr

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [189]:
copied

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [201]:
copied1 = arr

In [191]:
arr

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [202]:
copied1

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [203]:
np.delete(copied1,1,axis=1)

array([[10],
       [12],
       [14],
       [16],
       [18]])

In [205]:
arr

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])